### ISSUE TITLE
Not working on MacOSX High Sierra (10.13.6)

### ISSUE THREAD

**Issue by bogdanstoica35** [rockyluke/drac-kvm#11]
drac-kvm is not working on HighSierra, version **10.13.6** with go installed using brew, go version: **go1.11.1 darwin/amd64**

When running drac-kvm I get this:

`drac-kvm -h 10.107.1.121 -u root -p password
`
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12d78ea]

```
goroutine 1 [running]:
github.com/rockyluke/drac-kvm/vendor/github.com/Unknwon/goconfig.(*ConfigFile).GetValue(0x0, 0x1398031, 0x8, 0x1398d1b, 0xb, 0x0, 0x0, 0x0, 0x0)
	/Users/bogdan/go/src/github.com/rockyluke/drac-kvm/vendor/github.com/Unknwon/goconfig/conf.go:164 +0x4a
main.main()
	/Users/bogdan/go/src/github.com/rockyluke/drac-kvm/main.go:109 +0x436

```

**Comment by andybotting** [comment]
I just noticed this too. Using strace, I could see it was failing to find the ~/.drackvmrc file.

I just did `touch ~/.drackvmrc` and I'm in business.

**Comment by bogdanstoica35** [comment]
Thanks for the tip. Indeed, it works!

**Comment by rockyluke** [comment]
I'll fix that quickly. Thanks for the report.
