### ISSUE TITLE
Program crashes on Windows when ~/.drackvmrc isn't present

### ISSUE THREAD

**Issue by ajruckman** [rockyluke/drac-kvm#5]
This is an awesome utility. If only there was a way to enable weak Java algorithms with a flag rather than having to set it in the `java.security` file, and a way to ignore the invalid certificate popup with a flag too...

Here is my error:

```PS C:\Users\aj> drac-kvm -h 10.0.2.14 -u root -v 6 -p
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x68 pc=0x6b40c1]

goroutine 1 [running]:
github.com/rockyluke/drac-kvm/vendor/github.com/Unknwon/goconfig.(*ConfigFile).GetValue(0x0, 0xc042062090, 0x9, 0x772483, 0x4, 0x0, 0x0, 0x0, 0x0)
        D:/bin/gopath/src/github.com/rockyluke/drac-kvm/vendor/github.com/Unknwon/goconfig/conf.go:164 +0x51
main.main()
        D:/bin/gopath/src/github.com/rockyluke/drac-kvm/main.go:115 +0x410
```

I know a little bit about Golang, I'll try to see if I can figure it out when I get some time :)

**Comment by rockyluke** [comment]
Sorry for the long answer. I'll dig into it.

**Comment by rockyluke** [comment]
Thanks for the PR which solved that. Sorry for the delay, newborn at home 😄

**Comment by ajruckman** [comment]
Congratulations! :)
