### ISSUE TITLE
Virtual Media native library cannot be loaded

### ISSUE THREAD

**Issue by guardfox** [rockyluke/drac-kvm#6]
Hello,
while trying to reinstall  a  Dell R610 using a virtual CD ISO, virtual media menu is broken with following error:

![image](https://user-images.githubusercontent.com/9665841/43990964-674d6e38-9d63-11e8-8f8c-6a227c3ac1b0.png)

Would be very  useful to use this feature . Not necessary to be a bug imho.

P.S. Forgot to mention that was testing on OSX 10.12.6.

Thank you.

**Comment by rockyluke** [comment]
Sorry for the long answer. I'll dig into it.

**Comment by 0kulist** [comment]
Just compare browser generated .jnlp with the drac-kvm version and complement the difference.
For example for drac v6, add to the drac6.go the next resource section:  <resources os="Mac OS X" arch="x86_64">
    <nativelib href="https://{{ .Host }}:443/software/avctKVMIOMac64.jar" download="eager"/>
   <nativelib href="https://{{ .Host }}:443/software/avctVMMac64.jar" download="eager"/>
  </resources>

**Comment by 0kulist** [comment]
```
 <resources os="Mac OS X" arch="x86_64">
    <nativelib href="https://{{ .Host }}:443/software/avctKVMIOMac64.jar" download="eager"/>
   <nativelib href="https://{{ .Host }}:443/software/avctVMMac64.jar" download="eager"/>
  </resources>
```
